#mybatis:
#    mapper-locations: classpath:mappers/*xml
#    type-aliases-package: com.example.mybatis.entity
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 8080
spring:
    application:
        name: myDemo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: 333
        url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC
        username: root
mybatis-plus:
    configuration:
        lazy-loading-enabled: true
        aggressive-lazy-loading: false
        lazy-load-trigger-methods: equals,clone,hashCode,toString
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        cache-enabled: true
